name: 'Google chat Notify'
description: 'Notify a group with message'
inputs:
  key:
    description: 'google chat key'
    required: true
  space:
    description: 'google chat space'
    required: true
  token:
    description: 'google chat token'
    required: true
outputs:
  notify:
    description: 'A notify was sent to group!'
runs:
  using: 'node16'
  main: 'build/index.js'